config/routes.rb
Rails.application.routes.draw do
  get    'signup'  => 'users#new'
  get    'profile' => 'users#show'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :photos, only: [:index, :new, :create, :show, :destroy]
  resources :hearts, only: [:create, :destroy]
  

  root 'photos#index'

end

app/models/heart.rb
class Heart < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo

  validates_uniqueness_of :user_id, :scope => :photo_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_many :hearts
  has_many :users, through: :hearts
  validates :url, presence: true, uniqueness: true


  def heart_count
    self.hearts.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hearts
  has_many :photos, through: :hearts

  validates :username, presence: true,
                       uniqueness: true
  has_secure_password
  # validates :password, presence: true,
  #                      length: { minimum: 5 },
  #                      confirmation: true

  # def password
  #   @password ||= BCrypt::Password.new(encrypted_password)
  # end

  # def password=(new_password)
  #   @password = BCrypt::Password.create(new_password)
  #   self.encrypted_password = @password
  # end

  # def authenticate(entered_password)
  #   self.password == entered_password
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController

  def create
  end

  def destroy
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    start = 0
    stop = 19
    @photos = Photo.all.order(created_at: :desc)[start..stop]
    if request.xhr?
      start = params[:start].to_i
      stop = params[:stop].to_i
      if Photo.last.id < start
        return 400
      end
      @photos = Photo.all.order(created_at: :desc)[start..stop]
      render '_photos.json', layout: false
    else
      render 'index'
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @hearts = @photo.hearts.all.order(created_at: :desc)
  end

  def new
    render 'new'
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to @photo
    else
      @photo = Photo.find_by(url: params[:url])
      @hearts = @photo.hearts.all.order(created_at: :desc)
      flash.now[:notice] = "someone else beat you to this one!  here it is."
      render 'show'
    end
  end

  def destroy
    if !is_admin?
      flash.now[:error] = 'you don\'t have access to this area.  sorry.'
      render 'index'
    else
      photo = Photo.find(params[:id])
      photo.destroy
      redirect_to :root
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    if request.xhr?
      render 'new', layout: false
    end
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    p @user
    p params[:session][:password]
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      flash.now[:notice] = 'your login information was incorrect. puppies don\'t like hackers.'
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:notice] = 'you have successfully logged out.'
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    start = 0
    stop = 19
    @photos = @user.hearts.order(created_at: :desc)[start..stop]
    if request.xhr?
      start = params[:start].to_i
      stop = params[:stop].to_i
      if @photos.last.id < start
        return 400
      end
      @photos = @user.photos.order(created_at: :desc)[start..stop]
      render '/photos/_photos.json', layout: false
    else
      render 'show'
    end
  end

  def new
    @user = User.new
    if request.xhr?
      render 'new', layout: false
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    p old_password = params[:user][:password_old]
    if (@user.password == old_password) && @user.update(user_params)
      redirect_to @user
    elsif @user.password != old_password
      flash.now[:notice] = "your old password was incorrect.  puppies don't like hackers."
      render 'edit'
    else
      render 'edit'
    end
  end

  def destroy
    if is_admin? || current_user.id.to_s == params[:id]
      user = User.find(params[:id])
      user.destroy
      if !is_admin?
        log_out
      end
      flash.now[:notice] = 'you have successfully deleted your account.  we will miss you.'
      redirect_to photos_path
    else 
      flash.now[:error] = 'you don\'t have access to this area.  sorry.'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def is_authenticated?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def is_admin?
    current_user === User.find_by(username: "admin")
  end
end

app/views/hearts/_comment.html.erb
<%if heart.comment != '' %>
  <li class='list-group-item' id='<%= heart.id%>'>
    <i class='fa fa-quote-left'></i> <%=heart.comment%> <i class='fa fa-quote-right'></i>
    --<a href='/users/<%=heart.user_id%>'><%=heart.user.username%></a>
  </li>
<%end %>

app/views/hearts/_grid_hearts.html.erb
<div class = 'heart-buttons'><% if is_authenticated? %><% if is_admin? %><div class='admin-delete left'><a href='/photos/<%=photo.id%>/delete'>Delete Photo</a></div><%end%><form method='post' action='/hearts' id='heart' <%if (photo.hearts.find_by(user_id: current_user.id))%>class='hidden'<%end%>><input type='hidden' name='heart[user_id]' value='<%=current_user.id%>'><input type='hidden' name='heart[photo_id]' value='<%=photo.id%>'><label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label><button type='submit' class='icon'><i class='fa fa-heart-o'></i></button></form><form method='post' action='/hearts' id='unheart' <%if !(photo.hearts.find_by(user_id: current_user.id))%>class='hidden'<%end%>><input type='hidden' name='_method' value='delete'><input type='hidden' name='user_id' value='<%=current_user.id%>'><input type='hidden' name='photo_id' value='<%=photo.id%>'><label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label><button type='submit' class='icon'><i class='fa fa-heart' ></i></button></form><% else %><label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label><i class='fa fa-heart-o login'></i><div class='login-prompt' style='display: none;'>please <a href='/users/login'>log in</a> or <a href='/users/new'>sign up</a> to heart.</div><%end%></div>

app/views/hearts/_heart_buttons.html.erb
<div class = 'heart-buttons'>
  <% if is_authenticated? %>
    <% if is_admin? %>
      <div class='admin-delete left'>
        <a href='/photos/<%=photo.id%>/delete'>Delete Photo</a>
      </div>
    <%end%>
  <form method='post' action='/hearts' id='heart' <%if (photo.hearts.find_by(user_id: current_user.id))%>class='hidden'<%end%>>
    <input type='hidden' name='heart[user_id]' value='<%=current_user.id%>'>
    <input type='hidden' name='heart[photo_id]' value='<%=photo.id%>'>
    <div class='form-group'>
      <input type='text' class='form-control' name='heart[comment]' placeholder='What makes this so heartable?'>
    </div>
    <label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label>
    <button type='submit' class='icon'><i class='fa fa-heart-o'></i></button>
  </form>

  <form method='post' action='/hearts' id='unheart' <%if !(photo.hearts.find_by(user_id: current_user.id))%>class='hidden'<%end%>>
    <input type='hidden' name='_method' value='delete'>
    <input type='hidden' name='user_id' value='<%=current_user.id%>'>
    <input type='hidden' name='photo_id' value='<%=photo.id%>'>
    <label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label>
    <button type='submit' class='icon'><i class='fa fa-heart'></i></button>
  </form>
  <% else %>
  <label class='heart-count photo<%=photo.id%>'><%= photo.heart_count %></label><i class='fa fa-heart-o login'></i>
  <div class='login-prompt' style='display: none;'>please <a href='/users/login'>log in</a> or <a href='/users/new'>sign up</a> to heart.</div>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>


  <!-- Font awesome -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <link href='https://fonts.googleapis.com/css?family=Righteous|Gochi+Hand' rel='stylesheet' type='text/css'>




  <title>allthepuppies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="lightbox-background" style='display:none;'></div>
  <header>
  <nav class='navbar navbar-default'>
    <div class='col-md-10 col-md-offset-1'>
      <div class='container-fluid'>
      <div class='navbar-header'>
        <a class='navbar-brand' href='/photos'>all the <span>puppies</span></a>
        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#main-navbar-collapse' aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>
      <div class='collapse navbar-collapse' id='main-navbar-collapse'>
        <ul class='nav navbar-nav navbar-right'>
          <li><a href="/photos/new" class='attention'>add puppy</a></li>
          <%if is_authenticated?%>
            <!-- <#%if is_admin? %>
              <li><a href='/admin'>admin dashboard</a></li>
            <#%end%> -->
            <li><%= link_to 'my profile', user_path(current_user) %></li>
            <li><%= link_to "log out", logout_path, method:"delete"%></li>
          <%else%>
            <li><%= link_to 'sign up', new_user_path, class:'call-form' %></li>
            <li><%= link_to "log in", login_path, class: 'call-form'%></li>
          <%end%>
        </ul>
      </div>
      </div>
    </div>
  </nav>
    
  </header>
  <div class='main container-fluid col-md-10 col-md-offset-1'>
  <% if !flash[:notice].nil? && !flash[:error].nil? %>  
    <div class = 'panel flash-area'>
      <% flash.each do |name, msg| -%>
        <p><%= content_tag :div, msg, class: name %></p>
      <% end -%>
    </div>
  <% end %>
  <%= yield %>
  </div>
  <script type="text/javascript" src='/assets/salvattore.js'></script>
</body>
</html>

app/views/photos/_photos.json.erb
'[<% @photos.each do |photo| %>"<div class='panel panel-primary photo' id='photo<%=photo.id%>'><div class='panel-body'><a href = '/photos/<%=photo.id%>'><img src='<%= photo.url%>' class='img-responsive' /></a></div><div class='panel-footer'><%= render partial: '/hearts/grid_hearts', locals: {photo: photo} %></div></div>",<%end%>]'

app/views/photos/index.html.erb
<div id="columns" data-columns=''>
  <% @photos.each do |photo| %>
    <div class='panel panel-primary photo' id='photo<%=photo.id%>'>
      <div class='panel-body'><a href = '/photos/<%=photo.id%>'><img src='<%= photo.url%>' class='img-responsive' /></a></div>
      <div class='panel-footer'>
      <%= render partial: '/hearts/grid_hearts', locals: {photo: photo} %>
      </div>
    </div>
  <%end%>
</div>

app/views/photos/new.html.erb
<h1>add photo</h1>

<%= form_for :photo, url: photos_path, html:{class:'col-md-4 col-md-offset-4'} do |f| %>


  <div class='form-group'>
    <%= f.label :url, 'url' %><br>
    <%= f.text_field :url, class:'form-control'  %>
  </div>

  <div class='form-group'>
    <%= f.submit "add photo", class:'btn btn-default'%>
  </div>

<% end %>

app/views/photos/show.html.erb
<div class='text-center'>
  <div class='panel' style='border: none;'>
    <% if @errors %>
      <h3><%= @errors %></h3>
    <% end %>
  </div>
<div class='panel panel-primary photo single' id='photo<%=@photo.id%>'>
  <div class='panel-body'><img src='<%= @photo.url%>' class='img-responsive' /></div>
  <div class='panel-footer'>
  <%= render partial: '/hearts/heart_buttons', locals: {photo: @photo} %>
  </div>
  <ul class='list-group comments'>
    <% @hearts.each do |heart| %>
      <%if heart.comment != nil && heart.comment != ''%>
        <li class='list-group-item' id="<%= heart.id%>">
          <div><p><i class='fa fa-quote-left up'></i>&#9;<%=heart.comment%>   <i class='fa fa-quote-right down'></i>
                -- <a href='/users/<%=heart.user_id%>'><%=heart.user.username%></a></p>

        </div>
        <% if is_authenticated? %>
          <% if is_admin? %>
            <div class='admin-delete left'>
              <a href="/hearts/<%=heart.id%>/delete">Delete Comment</a>
            </div>
          <%end%>
        <%end%>
        </li>
      <%end %>
    <% end %>
  </ul>
</div>
</div>

app/views/users/edit.html.erb
<h1>edit profile</h1>

<%= form_for @user, html:{class:'col-md-4 col-md-offset-4'} do |f| %>
  <% if @user.errors.any? %>
    <div id='error_explanation'>
      <h2>
        sorry, you had <%= pluralize(@user.errors.count, 'error') %> that kept you from editing your account:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @old_password_error %>
    <div id='error_explanation'>
    <p><%=@old_password_error%></p>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :username, 'username' %><br>
    <%= f.text_field :username, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :password_old, 'old password' %><br>
    <%= f.password_field :password_old, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :password_new, 'new password' %><br>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :password_confirmation, 'confirm new password' %><br>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.submit 'update profile', class:'btn btn-default' %>
    <span class='right'><%= button_to 'delete profile', user_path(@user), method: :delete, data: {confirm: 'are you sure?'}, class:'btn btn-default' %></span>
  </div>

<% end %>

app/views/users/new.html.erb
<h1>sign up</h1>

<%= form_for @user, html:{class:'col-md-4 col-md-offset-4'} do |f| %>
  <% if @user.errors.any? %>
    <div id='error_explanation'>
      <h2>
        sorry, you had <%= pluralize(@user.errors.count, 'error') %> that kept you from creating an account:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :username, 'username' %><br>
    <%= f.text_field :username, class:'form-control'  %>
  </div>

  <div class='form-group'>
    <%= f.label :password, 'password' %><br>
    <%= f.password_field :password, class:'form-control'  %>
  </div>

  <div class='form-group'>
    <%= f.label :password_confirmation, 'confirm password' %><br>
    <%= f.password_field :password_confirmation, class:'form-control'  %>
  </div>

  <div class='form-group'>
    <%= f.submit class:'btn btn-default'%>
  </div>

<% end %>

app/views/users/show.html.erb
<% if is_authenticated? %>
  <%if current_user.id == @user.id %>
    <h1>hello, <%= @user.username %>!<span class='right'><a href="/users/<%=@user.id%>/edit"><button class='btn btn-default'>edit profile</button></a></span></h1>
    
    <h4>your current puppy hearts:</h4>
  <%else%>
    <h1><%= @user.username %>'s profile</h1>
    <% if is_admin? %>
      <form method='post' action="/users/<%=@user.id%>">
        <input type='hidden' name='_method' value='delete'>
        <input type='submit' value='Delete Profile' class='btn btn-default'>
      </form>
    <%end%>
    <h4>current puppy hearts:</h4>
  <%end%>

    
<%else%>
  <h1><%= @user.username %>'s profile</h1>
  <h4>current puppy hearts:</h4>
<%end%>
<div id="columns" data-columns=''>
  <% @photos.each do |heart| %>
    <div class='panel panel-primary photo' id='photo<%=heart.photo_id%>'>
      <div class='panel-body'><a href = '/photos/<%=heart.photo_id%>'><img src='<%= heart.photo.url%>' class='img-responsive' /></a></div>
      <div class='panel-footer'>
      <%= render '/hearts/grid_hearts', locals: {photo: heart.photo} %>
      </div>
    </div>
  <%end%>
</div>